version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - mvn clean install -DskipTests=true

artifacts:
  files:
    - target/*.jar
    - .ebextensions/** # optional
    - Procfile
    - Dockerrun.aws.json # if Dockerized

