version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven dependencies..."
      - mvn install -DskipTests -Dmaven.repo.local=/root/.m2/repository
  pre_build:
    commands:
      - echo "Starting pre-build..."
  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Preparing artifact for deployment..."

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

