version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - mvn clean package -DskipTests=true
      - cp target/*.jar application.jar # copy the jar to root with expected name

artifacts:
  files:
    - application.jar
    - .ebextensions/**       # optional: configs for EB
  discard-paths: yes         # ensures flat structure (no folders inside zip)

